name: 'Radicati Content Base'
description: 'Base content setup for Radicati sites.'
type: 'Content'
recipes:
  - radicati-recipe-media
install:
  - paragraphs
  - field
  - field_ui
  - text
  - datetime
  - filter
  - editor
  - ckeditor5
  - text_field_formatter
  - link
  - options
  - telephone
  - entity_reference_revisions
  - file
  - field_group
  - taxonomy
  - menu_link_content
  - menu_ui
  - path
  - pathauto
  - blazy
  - editor
  - slick
  - type_tray
config:
  import:
    field: "*"
    field_ui: "*"
    text: "*"
    datetime: "*"
    text_field_formatter: "*"
    paragraphs: "*"
    field_group: "*"
    taxonomy: "*"
    menu_link_content: "*"
    menu_ui: "*"
    path: "*"
    pathauto: "*"